Checking domainRecord in case it's undefined
EdgeApp/edge-devops pull request #11
Opened 2021-04-28 17:30 UTC by jacobburrell

Ran into issue with blank 'domainRecord' so I checked in the iteration of utils 'getProvisionSettings' before continuning.

2021-04-28 18:45 UTC, samholmes commented on provisions/digitalocean/util.ts
> +      if (domainRecord) {
Why would domainRecord be undefined? Seems like there's a bug in `getDomainRecords`?

2021-05-03 17:55 UTC, samholmes requested changes

2021-05-03 17:55 UTC, samholmes commented on provisions/digitalocean/util.ts
> +          }
White-space formatting needs fixing. Run `deno fmt provisions/` to format all the TS files in `provisions/` dir (https://deno.land/manual/tools/formatter).

Tip: For Deno, you can add the Deno VS Code plugin to use deno's built in format command in your editor. Then add .vscode/settings.json:

```json
{
  "deno.enable": true,
  "deno.lint": true,
  "deno.unstable": true,
  "[typescript]": {
    "editor.defaultFormatter": "denoland.vscode-deno"
  },
  "prettier.requireConfig": false
}
```

This is what I have included in the project for my editor settings to get the helpful auto formatting and linting.

2021-05-03 17:55 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  }));
Below the TLD assignment, add an assertion that checks if TLD is in `domainsResBody.domains`. This is specifically for `opt.tld`, so include `opt.tld != null` in your assertion. Exit with a user error if assertion fails.

2021-05-03 17:55 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  });
I think in our discussion we've established that the issue wasn't with undefined/null values in domain_records array from DO API, but rather the TLD used not being available in the DO account. We don't need this filter.

2021-05-03 19:39 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  });
Right, forgot to remove it after I adjusted from the old if statement checking within the for loop of domainRecords.

2021-05-03 20:19 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  }));
How about adding a validation to the prompt?

`validate: (tld: string) => accountDomains.some(({name}) => name === tld),`

So we would now have:

`  // Top-level Domain:
  const TLD = opt?.tld ?? (await Select.prompt({
    message: "Select top-level domain",
    validate: (tld: string) => accountDomains.some(({name}) => name === tld),
    options: domainsResBody.domains.map((
      obj: { name: string; ttl: number },
    ) => ({
      name: obj.name,
      value: obj.name,
    })),
  }));`

2021-05-03 20:29 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +          }
Added plugin and ran **fmt** manually

2021-05-03 20:32 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  }));
Need some details for opt.tld not being null.

Aren't all the options, optional?

```
interface ProvisionOptions {
  tag?: string;
  token?: string;
  **tld?: string;**
  hostname?: string;
  volumeSizeGb?: number;
  region?: string;
  dropletSize?: string;
  sshKeyNames?: string[];
}
```

So like other options, it seems that if the option isn't provided, we are prompting the user for one:
`opt?.tld ?? (await Select.prompt`

What am I missing?

2021-05-03 21:33 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  }));
If the `opt.tld` is provided (defined from a config file), then this will skip the prompt entirely. Because the prompt is skipped, we cannot guarantee that the provided TLD is present in the domains on the account. An assertion that it is in the account domains would give us that guarantee.

2021-05-03 21:37 UTC, samholmes commented on provisions/digitalocean/index.ts
> +  --config config.json
Although the double-slash is a valid JavaScript comment, the code represented in this multi-line comment is actually shell script (bash). This is why the back-ticks where used; it was the only valid way to do an inline comment in the shell.

The reason why we want all of this code in the comment here to be valid shell script is so that we can trivially copy and paste to run without much modification.

2021-05-05 19:51 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  }));
Understood.

How about forcing a selection in case there's an error?

```
  const promptDomainSelection = (await Select.prompt({
    message: "Select top-level domain",
    validate: (tld: string) => accountDomains.some(({ name }) => name === tld),
    options: domainsResBody.domains.map((
      obj: { name: string; ttl: number },
    ) => ({
      name: obj.name,
      value: obj.name,
    })),
  }));

  // Top-level Domain:
  let TLD = opt?.tld ?? promptDomainSelection

  // If TLD is invalid, prompt for a selection of a valid domain
  if (accountDomains.find((domain) => domain.name == TLD) === undefined) TLD = promptDomainSelection
```

2021-05-05 22:37 UTC, samholmes requested changes

2021-05-05 22:37 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  if (accountDomains.find((domain) => domain.name == TLD) === undefined) TLD = await promptDomainSelection()
Instead of prompting for domain selection, we should probably just exit with an error. The reason why is so that way we are explicitly letting the user know that there is an issue with their config, rather than being silent about it.

2021-05-07 17:28 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  if (accountDomains.find((domain) => domain.name == TLD) === undefined) TLD = await promptDomainSelection()
Could we do both?

Provide a big obvious error message and prompt for a fix?
Maybe it would be best to exit to force fixing the config file.

2021-05-10 06:31 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  if (accountDomains.find((domain) => domain.name == TLD) === undefined) TLD = await promptDomainSelection()
I like the way you handled it a bit further down, allowing the user option to exit or replace.

```
const action = await Select.prompt({
        message: `${type} record for '${domain}' already exists`,
        options: [
          {
            name: "Exit",
            value: "exit",
          },
          {
            name: "Replace",
            value: "replace",
          },
        ],
      });
```

2021-05-12 17:05 UTC, jacobburrell commented on provisions/digitalocean/util.ts
> +  const TLD = opt?.tld ?? await promptDomainSelection()
I added the option to choose a new domain if the problem with the config file, which reuses the function.

2021-05-12 17:08 UTC, samholmes approved these changes

2021-05-12 17:09 UTC, merged