Add private Github cloning
EdgeApp/edge-devops pull request #15
Opened 2021-05-21 01:07 UTC by jacobburrell

Adding ability to add private key for ssh to authenticated cloning of remote private git repo

Added Github to known hosts, though will have to add the other known hosts such as Gitlab for SSH to clone in the script.

2021-05-21 21:20 UTC, samholmes requested changes
Minor changes and some comments.

2021-05-21 21:20 UTC, samholmes commented on provisions/digitalocean/config.sample.json
> +  "gitSshKey": "/Users/edgy/.ssh/provisions/key",
nit: `"gitSshKey": "/Users/you/.ssh/provisions/key",`

2021-05-21 21:20 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  // Check for Droplet access
Line 406 is cruft?

2021-05-21 21:20 UTC, samholmes commented on edge-server/project.sh
> +echo "Adding SSH key to ~/home/edgy/.ssh/github"
`echo "Adding SSH key to ~/.ssh/github"`

2021-05-21 21:20 UTC, samholmes commented on edge-server/project.sh
> +mkdir ~/.ssh
`mkdir -p ~/.ssh` will not throw if dir already exists.

2021-05-21 21:20 UTC, samholmes commented on edge-server/project.sh
> +    > ~/.ssh/github
What are the replacements for?

2021-05-22 00:44 UTC, jacobburrell commented on edge-server/project.sh
> +    > ~/.ssh/github
For some reason, while the ssh private key is passed correctly via an env. variable, **it has whitespaces removed**, so I specified to use contents between default ssh comment which allows the ssh key to be added as the format needs to be specific.

2021-05-22 00:45 UTC, jacobburrell commented on edge-server/project.sh
> +mkdir ~/.ssh
Originally I did try -p though I ran into some issue.

I can add it back in.

2021-05-22 00:53 UTC, jacobburrell commented on edge-server/project.sh
> +    > ~/.ssh/github
There probably is a better way to ensure the text isn't modified in the first place, I lack the best method to do though.

2021-05-24 15:51 UTC, samholmes requested changes

2021-05-24 15:51 UTC, samholmes commented on edge-server/project.sh
> +    > ~/.ssh/github
Replace `echo $GITKEY | ...` with `echo "$GITKEY"`. This will preserve the new-lines (bash is weird).

2021-05-24 15:51 UTC, samholmes commented on edge-server/project.sh
> +mkdir ~/.ssh
What issues were you running into? Make sure after adding it back you test that things work.

2021-06-08 23:41 UTC, samholmes commented
This branch shows a working example of this feature: https://github.com/EdgeApp/edge-devops/tree/sam/gitkey

2021-06-09 16:14 UTC, samholmes requested changes
Looking good so far. Final touches needed. Also if you don't mind changing the git comments to use the imperative mood (change all verbs to their imperative form; adding/added/adds to add, etc), then that'll be nice as well. :)

2021-06-09 16:14 UTC, samholmes commented on provisions/digitalocean/index.ts
> +    ? await Deno.readTextFile(config?.gitSshKey)
nit: `await Deno.readTextFile(config.gitSshKey)`

2021-06-09 16:14 UTC, samholmes commented on edge-server/install.ubuntu.sh
> +sudo systemctl restart caddy
Remove 42-54; code dup

2021-06-09 16:14 UTC, samholmes commented on edge-server/project.sh
> +echo "Cloning $PROJECT_URL..."
Remove unnecessary whitespace character

2021-06-11 06:29 UTC, jacobburrell commented
Updated all points mentioned. Ready to merge @samholmes ?

2021-06-11 17:15 UTC, samholmes approved these changes

2021-06-11 17:15 UTC, samholmes commented on provisions/digitalocean/index.ts
> +    ? await Deno.readTextFile(config.gitSshKey)
This fixup should have been on the previous commit. A bit of git surgery is all that's needed here to have this moved:

1. `git rebase -i master`
2. edit Add SSH key for Github to config
3. Make the fix on this file line 64
4. `git rebase --continue` (that should be the command IIRC)

Because we apply the fix to 'Add SSH key for Github to config' (4c67f4b9668f7018f7012140ea462ba44ba1aeca) this change on eb44d5742aeae84dffebb97f8058ce650ac87616 will become a noop and we should be good to go.

2021-06-11 17:32 UTC, merged