New sync server install scripts
EdgeApp/edge-devops pull request #2
Opened 2020-12-22 01:28 UTC by samholmes

2021-02-19 21:44 UTC, paullinator requested changes

2021-02-19 21:44 UTC, paullinator commented on .vscode/settings.json
> +  "deno.enable": true,
Per @swansontec 's request, do not include code editor files in git

2021-02-19 21:44 UTC, paullinator commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
Can the node name simply be the host name of the computer. That would be one less thing to specify

2021-02-19 21:44 UTC, paullinator commented on provisions/sync-server-digitalocean.ts
> +const TOKEN = await Secret.prompt("DigitalOcean API key");
What kind of magic is this? How are you doing an await outside of an async function

2021-02-19 21:44 UTC, paullinator commented on provisions/sync-server-digitalocean.ts
> +console.log("done!");
Where do you provision and attach the volume?

2021-02-19 23:52 UTC, samholmes commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
The node name must include a fully qualified domain for the cluster node; we are using the internal domain name.

2021-02-19 23:53 UTC, samholmes commented on provisions/sync-server-digitalocean.ts
> +const TOKEN = await Secret.prompt("DigitalOcean API key");
The deno runtime supports top-level await.

2021-02-19 23:54 UTC, samholmes commented on provisions/sync-server-digitalocean.ts
> +console.log("done!");
How did I miss that... I'll need to add more script.

2021-02-20 00:04 UTC, paullinator commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
That's fine. You can simply add the host name to the domain name. And still no need to specify this environment variable

2021-02-20 00:22 UTC, samholmes commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
@paullinator What do you mean exactly? If I understand correctly, we need to supply the couch installation with a node name similar to `couchdb@subdomain-int.edge.app` in order for the installation configuration to be set up properly. If we don't use an environment variable here, how will we pass this configuration down to this step in the procedure?

2021-02-20 00:32 UTC, paullinator commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
You can grab the host name by using the command line `hostname` And it looks like you already set the domain name to `edge.app`

2021-02-20 01:10 UTC, samholmes commented on misc/install-couch-caddy.sh
> +echo "couchdb couchdb/nodename string $COUCH_NODE_NAME" | debconf-set-selections
Oh, got it. Thanks for clarifying. Yes, I can change this to use the `hostname` from the CLI op, and append `-int.edge.app`. This would mean that this script will only work with `edge.app` domains, but I'm okay with that.

2021-02-24 02:33 UTC, paullinator requested changes

2021-02-24 18:56 UTC, samholmes commented
From discussions with Paul:

- Check droplet name exist and fail if taken
- Fail on domain record exist
- Add an optional flag (config) that allows you to overwrite prompts

- Add an option for TLD (default to edge.app)
- Fix install-couch-caddy.sh to allow for non-clustered couchdb install

2021-02-24 20:03 UTC, samholmes commented
I just recalled, that we're missing an important environmental dependency: ab-sync. How can we install this dependency; we need a distribution mechanism for it. I'll follow up with William about this.

2021-03-02 19:23 UTC, samholmes commented
This devops script utilized the `yarn setup` script that is an open PR on the sync-server: https://github.com/EdgeApp/edge-sync-server/pull/36

2021-03-03 17:26 UTC, samholmes commented on provisions/sync-server-digitalocean/index.ts
> +})).map((value: string) => parseInt(value));
Add a `config.sshNames: string[]` field to config to match names in the available ssh keys. If a name is not present in the response then exit.

2021-03-03 17:32 UTC, samholmes commented on provisions/sync-server-digitalocean/index.ts
> +`;
Make this generic. Motivation: this entire script should be made into a generic library and another script should be created specifically for sync-server. This would act as the first use-case/example on how to use the provision library.

2021-03-03 17:35 UTC, samholmes commented on provisions/sync-server-digitalocean/index.ts
> +`;
The user_data script should redirect output/errors to a log file for debugging.

2021-03-03 17:37 UTC, samholmes commented on install-sync-digitalocean.sh
>  ## curl -o- https://raw.githubusercontent.com/EdgeApp/edge-devops/master/install-sync-digitalocean.sh | bash
Look to see if digitalocean will dump user_data logs somewhere.

2021-03-09 00:37 UTC, merged