Flag to disable DNS record creation
EdgeApp/edge-devops pull request #23
Opened 2021-12-25 00:25 UTC by samholmes

2021-12-27 19:31 UTC, samholmes commented on provisions/digitalocean/util.ts
> +  config: Config,
So the motivation here is to deprecate `ProvisionOptions` in favor of just accepting a `Config` parameter (less type transformations; simpler codebase this way). Perhaps a deprecated comment with a "TODO" is warranted. Or, we can add the field to the existing type for now and then save this effort/motivation for later. I'm open to suggestions.

2022-01-04 17:48 UTC, swansontec requested changes
Just noticed one little thing to fix.

2022-01-04 17:48 UTC, swansontec commented on provisions/digitalocean/index.ts
> +      const COUCH_MODE = config?.couchClusterSeedList.length != null &&
Now that `config` & `couchClusterSeedList` are always present, we need to change this to `length > 0` and drop the null checks.

2022-01-06 00:24 UTC, samholmes commented on provisions/digitalocean/index.ts
> +      const COUCH_MODE = config?.couchClusterSeedList.length != null &&
Good catch

2022-01-06 00:31 UTC, samholmes commented on provisions/digitalocean/index.ts
> +      const COUCH_MODE = config?.couchClusterSeedList.length != null &&
I fixed up d701b62 to include the null-check removal for `config`.

2022-01-06 19:28 UTC, swansontec approved these changes

2022-01-06 19:44 UTC, merged